### ISSUE TITLE
NHK World doesn't working

### ISSUE THREAD

**Issue by pp5ere** [Free-IPTV/Countries#196]
Hi. First congratulation for release this amazing IPTV free list. Second my favorite channel doesn't working. I'll be glad if it working again. Thank you so much.

**Comment by Free-IPTV** [comment]
> 
> 
> Hi. First congratulation for release this amazing IPTV free list. Second my favorite channel doesn't working. I'll be glad if it working again. Thank you so much.

Hi @pp5ere 

thank you. :-) NHK World from JP01_JAPAN works absolutely flawlessly in Kodi 18 and 19 as well as in VLC.Player in Windows. It only takes a few seconds for the stream to start, so there is nothing I can do about that.

What kind of player do you use?

**Comment by pp5ere** [comment]
I tried with kodi 18.9 on raspberry (OSMC) and with SS IPTV on LG TV. In both nothing work. Thank you

**Comment by Zhoro-111** [comment]
> I tried with kodi 18.9 on raspberry (OSMC) and with SS IPTV on LG TV. In both nothing work. Thank you

Working to me also on 4 different players (IPTV Smarters,TIVIMATE,KODI and VLC)..strange !!!

**Comment by Free-IPTV** [comment]
Hi @ pp5ere 

In my m3u is the original stream from NHK World:
https://nhkworld.webcdn.stream.ne.jp/www11/nhkworld-tv/global/2003458/live.m3u8


From the homepage: 
https://www3.nhk.or.jp/nhkworld/en/live/

If that doesn't work for you, the problem is probably with your system. As I wrote, it works fine under Kodi 18 and 19 as well as in the VLC player. Issue closed.
