### ISSUE TITLE
Access to private repo

### ISSUE THREAD

**Issue by samuelhalle** [Free-IPTV/Countries#252]

**Comment by GitHub-User101** [comment]
I would also like access to your private repo.

**Comment by de-jourdain** [comment]
I would like to have access to the new repo.

**Comment by multichoyce** [comment]
May I get access too please?

**Comment by maiamos** [comment]
Please, I would like access to your private repo

**Comment by iSp3kter** [comment]
I would like access to your private repo

**Comment by FinallyCanuck** [comment]
What is the process for requesting access for legitimate personal use? If I missed it in the README, I apologise.

**Comment by Zhoro-111** [comment]
> What is the process for requesting access for legitimate personal use? If I missed it in the README, I apologise.



> What is the process for requesting access for legitimate personal use? If I missed it in the README, I apologise.

You're ok,just to write here needed.Now you and others must wait for Free-IPTV approval.Thank you !

**Comment by mainhill** [comment]
Please, give me access to the new repo. And shame to the stealers.

**Comment by Pankovas** [comment]
Can I also have access please? Thank you.

**Comment by Pankovas** [comment]
Hi, Can I have access please? Thank you !

**Comment by Pankovas** [comment]
Hi, Could I have access please? Thank you!

**Comment by NickyP11** [comment]
Hi,
Could I have access please? Thank you!

**Comment by KompressR** [comment]
May I also have access to the repo? Thank you!

**Comment by santiogro000** [comment]
Hi I read the readme, and I want to have access to your repo :)

**Comment by rduetsch** [comment]
Hi i read the readme, and i am not contributer in iptv-org i am interested to have access to the new repo. Thank you for your work and i try to contribute where ever i can.

**Comment by mcalistri** [comment]
Hello, first of all my 1000M Kudos to the main developer of this code repo for IPTV, it has been working flawlessly until the hack issue with HD resolution! I would like very much to get access to it again. I'm just a private user, I have not interest to sell/hack or make non etic actions at all, just enjoy this work. I'm st/by for the directions.
Many thanks for your kind attention!

Regards,

**Comment by infid0** [comment]
I've discovered this fantastic list some days ago and now for some f*****g thief is not more available! Thank you for your hard work and please, accept me for the private repo. Thank you so much.

**Comment by bernie1968** [comment]
Hi, can i have the new private repo? Greetings from Bernie and keep up the good work!

**Comment by getsam123** [comment]
Hi, Can I get access to your private repo, this was an amazing source of content for past few days for me. I would be amazing to get it again. Thanks.

**Comment by Mennaruuk** [comment]
Would love access to the new repo. Wanna keep watching my fav channels.

**Comment by Free-IPTV** [comment]
Hi 

**for all except KompressR** (New user, read the rules!)
thank you for your interest in our new private repo. :-)

Our Free-IPTV project is always a lot of work. We always have in the old repo
the streams are regularly updated and new streams offered free of charge.

**Therefore we ask for a small donation. The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

The minimum donation of 3 months is 3 EUR. I thank you!**

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

**Comment by flankerisded** [comment]
May i get access to the repo

**Comment by de-jourdain** [comment]
Although I recognize the commitment and dedication on these lists (especially on the 'non-pluto'), the 'pluto' lists do not behave the way I understand they should.

Let me explain:
Currently, the lists always point to propaganda and breaks in English, even if it is Pluto Germany, or Pluto 'any other language'.

That way, every channel that I add to my personal list must invariably be worked on by me, so that I edit the link, so that the variable 'region' (as marketing region for 'DE') is added and is functional, in addition to reorganizing the channels and the groups by themes (News, Films, Kids, Comedy, etc ...) not in alphabetical order, and always adjust the icons as transparent PNG, mainly for channels in the 'non-pluto' lists, editing the icons or redoing it, by myself. 

I also have to remove links with geoblocking, which unfortunately do not work outside their respective territories, even being open in its respective countries. Yes, I watch channels in some languages. Yes, it is for personal use only. Yep, I am a perfectionist. ;-)

So, considering the lists as references, I agree. However, as the lists do not fully meet my personal demand, I always have to rework them for my use. If you want my collaboration to share what I have done, for collaboration and exchange, Ok.

**Comment by Free-IPTV** [comment]
> 
> 
> May i get access to the repo

Our Free-IPTV project is always a lot of work. We always have in the old repo
the streams are regularly updated and new streams offered free of charge.

Therefore we ask for a small donation. The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

The minimum donation of 3 months is 3 EUR. I thank you!

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

After this process you will receive an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

Thank you. :-)

**Comment by Free-IPTV** [comment]
> 
> 
> Although I recognize the commitment and dedication on these lists (especially on the 'non-pluto'), the 'pluto' lists do not behave the way I understand they should.
> 
> Let me explain:
> Currently, the lists always point to propaganda and breaks in English, even if it is Pluto Germany, or Pluto 'any other language'.
> 
> That way, every channel that I add to my personal list must invariably be worked on by me, so that I edit the link, so that the variable 'region' (as marketing region for 'DE') is added and is functional, in addition to reorganizing the channels and the groups by themes (News, Films, Kids, Comedy, etc ...) not in alphabetical order, and always adjust the icons as transparent PNG, mainly for channels in the 'non-pluto' lists, editing the icons or redoing it, by myself.
> 
> I also have to remove links with geoblocking, which unfortunately do not work outside their respective territories, even being open in its respective countries. Yes, I watch channels in some languages. Yes, it is for personal use only. Yep, I am a perfectionist. ;-)
> 
> So, considering the lists as references, I agree. However, as the lists do not fully meet my personal demand, I always have to rework them for my use. If you want my collaboration to share what I have done, for collaboration and exchange, Ok.

And what do you mean to say to me now ??? Sorry, there is already a lot of work in the repo and many issues today. Our lists have the most important tags. The name, a logo, the tag group as a country. Our m3u´s work in Kodi, in the VLC player and in many apps.

You don't have to adjust anything. The lists correspond to the M3U standard. If our lists in an app do not run properly, the APP is not properly programmed.

**Comment by flankerisded** [comment]
Can i pay without or not and
Keep up with good work

**Comment by Free-IPTV** [comment]
> 
> 
> Can i pay without or not and
> Keep up with good work

Here the Text again!!!

Our Free-IPTV project is always a lot of work. We always have in the old repo
the streams are regularly updated and new streams offered free of charge.

Therefore we ask for a small donation. The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

The minimum donation of 3 months is 3 EUR. I thank you!

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

After this process you will receive an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

Thank you. :-)

**Comment by flankerisded** [comment]
Can i get it for free please

**Comment by Free-IPTV** [comment]
**The donation is ONLY for the daily work at the m3u´s. It is not for the streams**, they are free. If our extensive work is not even worth 1 EUR a month to you, then I still ask myself why we do our work at all. Think about it. ;-)

**Comment by samuelhalle** [comment]
Allright nevermind, I was wishing to collaborate, but not pay. Thanks.

**Comment by mcalistri** [comment]
You are extremely right!

The only little detail is that in country as where I'm living now 
(Brazil) the currency exchange with Euro is very disadvantageous, in any 
case the amount of 1 Eur/month is more symbolic than real.

And I support your initiative and philosophy!

Regards,

(Myself)



Il 05/04/21 13:14, Free-IPTV ha scritto:

**Comment by Free-IPTV** [comment]
Hi @samuelhalle,

do not close the ISSUE! There are some open comments. Thank you!

**Comment by Free-IPTV** [comment]
> 
> You are extremely right! The only little detail is that in country as where I'm living now (Brazil) the currency exchange with Euro is very disadvantageous, in any case the amount of 1 Eur/month is more symbolic than real. And I support your initiative and philosophy! Regards, (Myself)
> […](#)

You are welcome to donate more if the 1 EUR per month is too little for our work. :-)

**Comment by leonardoivo** [comment]
Dear,
   The euro is R$6,70 from Brazil.

**Comment by Free-IPTV** [comment]
> 
> 
> Dear,
> The euro is R$6,70 from Brazil. I am Brazilian. Here euro is expensive.

Please no send in  R$. Only EUR or US$ ;-)

**Comment by leonardoivo** [comment]
I just wanted to show the Euro quote in Brazil. The change Real to Euro.

**Comment by leonardoivo** [comment]
three euros is a good value. The problem for me and how to pay other than through Paypal

**Comment by Free-IPTV** [comment]
> 
> 
> three euros is a good value. The problem for me and how to pay other than through Paypal

3 euros for 3 months, see it for us as an estimate for the immense work.

**Comment by flankerisded** [comment]
Do we have to pay so then we can get access to the private repo?

**Comment by Free-IPTV** [comment]
> 
> 
> Do we have to pay so then we can get access to the private repo?

NO, THE ACCESS TO THE NEW REO IS FREE, ALL THE STREAMS ARE FREE! I have explained what the donation is about.

**Comment by mcalistri** [comment]
But the free link for me, which I'm watching Italian programs, _shows 
just 1 channel available_ (using the old shortened link published on 
github).

Regarding giving an higher offer, my comment was related to the fact 
that by making a direct comparison Europe/Brazil in terms of salary:

1.000 Euros vs. 1000 Reais, for a Brazilian user it is like an European 
one, being paying 6,70X3 =20,1 Euros for the IPTV access.

In any case I agree to pay 3 Eur/Month because your effort worth a merit 
and the quality of your service (HD streams) is very good.

Regards,

(MySelf)

Il 05/04/21 15:45, Free-IPTV ha scritto:

**Comment by leonardoivo** [comment]
I agree also pay.

**Comment by GitHub-User101** [comment]
The idea to charge for free ip streams is ridiculous. The streams are free. I thought you were sharing a personal list that you made for yourself. This isn't a business, no one asked for daily updates. Now that you are charging people are going to expect all links to work and will probably want additional free streams and better organization of the streams to fit their personal needs. This will also open you up to lawsuit from streaming services like Pluto, Redbox, Stirr, etc. They also are doing a lot of work to create and provide the channels without forcing a donation on the public. I'm sure they will not approve of you profiting off them. You accused iptv-org of stealing your list but they are not requesting a donation for their lists. Nothing you are offering is yours to offer, it's the equivilant of selling a pirated movie or in your case mandating a "donation" for it. If you want everyone to know you worked on a channel, then add a watermark. DON'T CHARGE FOR SOMETHING THAT ISN'T YOURS TO BEGIN WITH.

Anyone from Canada or USA. This site offers a good selection of free and legal channels. They even have a private roku channel.
https://thefrugalstreamer.blogspot.com/p/free2viewtvpage1.html

Anyone else looking for station they lost because of Free-IPTV can try here. You can make your own list (and they have icons too).
https://hlscat.com/

**Comment by Free-IPTV** [comment]
Hi @GitHub-User101!

It doesn't say anywhere and we NEVER claimed that access to the private repo would cost anything. Just like before, the streams are all free!

Don't tell such a bullshit here! Are you also one of those angry people who started a hate speech against me?

You are out of here!

**Comment by Free-IPTV** [comment]
> In any case I agree to pay 3 Eur/Month because your effort worth a merit and the quality of your service (HD streams) is very good.

HI @all!!!!

To finally make it clear here, the agitation against me is starting again. 

**1. The streams are free!
2. Access to the new repo is free**

Is a lot of work worth nothing anymore? The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the NEW PRIVATE repo!
