### ISSUE TITLE
New Repo

### ISSUE THREAD

**Issue by de-jourdain** [Free-IPTV/Countries#253]
Hi. I would like to have access to the new repo.

**Comment by Free-IPTV** [comment]
Hi @de-jourdain,

thank you for your interest in our new private repo. :-)

Our Free-IPTV project is always a lot of work. We always have in the old repo
the streams are regularly updated and new streams offered free of charge.

Therefore we ask for a small donation. The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

The minimum donation of 3 months is 3 EUR. I thank you!

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

**Comment by Free-IPTV** [comment]
Hi @all

**The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the PRIVATE repo!**

**Comment by Free-IPTV** [comment]
Hi @all

**The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the PRIVATE repo!**

**Comment by Free-IPTV** [comment]
Hi @all

**The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the PRIVATE repo!**
