### ISSUE TITLE
Honest user on Kodi, new repo request

### ISSUE THREAD

**Issue by Gargoylesmiles** [Free-IPTV/Countries#255]
Thanks for all you do. I got to know about your link because I use Hypnotix on my laptop but used your link for Kodi on my TV. Please grant me access to the new repo.

**Comment by Free-IPTV** [comment]
Hi @Gargoylesmiles,

thank you for your interest in our new private repo. :-)

Our Free-IPTV project is always a lot of work. We always have in the old repo
the streams are regularly updated and new streams offered free of charge.

Therefore we ask for a small donation. The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

The minimum donation of 3 months is 3 EUR. I thank you!

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

**Comment by Gargoylesmiles** [comment]
@Free-IPTV Thanks for your response. Will Hypnotix get a concession?

**Comment by Free-IPTV** [comment]
> 
> 
> @Free-IPTV Thanks for your response. Will Hypnotix get a concession?

Hypnotix will continue to have access.  I wrote to them in their repo a few days ago, but nobody answers. The new access must urgently be clarified. Hypnotix will then still be able to use our m3u's.

**Comment by Free-IPTV** [comment]
> 
> 
> @Free-IPTV Thanks for your response. Will Hypnotix get a concession?

Look there: https://github.com/linuxmint/hypnotix/issues/124

**Comment by Free-IPTV** [comment]
Hi @all

**The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the PRIVATE repo!**
