### ISSUE TITLE
Acesse to list private and solicitation to contribuite

### ISSUE THREAD

**Issue by leonardoivo** [Free-IPTV/Countries#257]
Dear,
I am user the list, also here Even before that incident I was looking forward to more suggestions for new channels. I would like to have access to this new list and be able to contribute with or without access to it. Thanks in advance.
Graciously,

**Comment by leonardoivo** [comment]
I would like to say that I will follow all the conditions established by you.

**Comment by bernie1968** [comment]
Can I have the private repo? I really like your updates, keep up the good work!!!

**Comment by Free-IPTV** [comment]
Hi @leonardoivo and @bernie1968,

thank you for your interest in our new private repo. :-)

Our Free-IPTV project is always a lot of work. We always have in the old repo
the streams are regularly updated and new streams offered free of charge.

Therefore we ask for a small donation. The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

The minimum donation of 3 months is 3 EUR. I thank you!

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

@leonardoivo! In the old repo you has create a fork and then... was nothing, nothing happened. Please pay attention to the new rules, they are also in the new repo, thank you.

**Comment by leonardoivo** [comment]
I linked the fork to my account these days. I do want to collaborate and I will try to raise a pull request on it. I have some links to go through. I haven't done it yet because I'm getting acquainted with git and github. I'm going to climb something on the fork tonight that I linked to before the rule you published this weekend.

**Comment by leonardoivo** [comment]
A suggestion. How about updating this list in other ways like email or private message, because not everyone knows how to use git.

**Comment by Free-IPTV** [comment]
> 
> 
> I linked the fork to my account these days. I do want to collaborate and I will try to raise a pull request on it. I have some links to go through. I haven't done it yet because I'm getting acquainted with git and github. I'm going to climb something on the fork tonight that I linked to before the rule you published this weekend.

Okay, read my text above. Thank you. :-)

**Comment by Free-IPTV** [comment]
> 
> 
> A suggestion. How about updating this list in other ways like email or private message, because not everyone knows how to use git.

As soon as you have received my invitation from the private repo, you have full access to all m3u's in the new repo. Downlowd works too!

**Comment by leonardoivo** [comment]
Dear, A question, did you send the invitation? If you have decided to send, how do I access it?

**Comment by leonardoivo** [comment]
I am user Github.

**Comment by Free-IPTV** [comment]
> 
> 
> Dear, A question, did you send the invitation? If you have decided to send, how do I access it?

The Way to access stand obove. Here Again the text for you:

Therefore we ask for a small donation. The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

The minimum donation of 3 months is 3 EUR. I thank you!

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

After this process you will receive an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

**Comment by leonardoivo** [comment]
I will make the donation soon. I don't usually use Paypal for donations or forms of payment. In general, I use boleto and other forms of donation. I have a paypal account, but I haven't used it in a long time. As soon as I can I will make the donation. Thank you for the contact.

**Comment by Free-IPTV** [comment]
Hi @all

**The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the PRIVATE repo!**

**Comment by leonardoivo** [comment]
A doubt,
   If you don't have a connection, why are they a condition for being able to access the private repository?

**Comment by Free-IPTV** [comment]
Have you ever worked on a repo that gets updates on a daily basis? We make updates every day and the streams all work! Take a look at the m3u's from the other providers, how many streams don't work. Sorry, I don't have the time to answer questions in the old repo all the time. I have to take care of my new private repo. Thank you for your understanding.
