### ISSUE TITLE
Access to private repo

### ISSUE THREAD

**Issue by Daddycool81** [Free-IPTV/Countries#261]
I would like access to the private repo, if possible. This has been a great hub and it sucks a few bad apples had to be a pain. Thanks.

**Comment by Free-IPTV** [comment]
Sorry, has you read the readme? 

Due to previous incidents, new accounts are currently a problem!

Sorry, i don't know you, some of these crooks will now try to get in here. Nothing against you but how can you convince me that you only want to use my m3u's privately?

Do you have a reference, a user who has been here on Github for a long time? Maybe you have a homepage where you can get more information?

**Comment by Daddycool81** [comment]
Has you read? Ok. I can see grammar isn’t your strong suit. I just liked the Aussie channel lists. Sorry your stuff is getting hosed, but don’t take it out on me. I will go elsewhere.

**Comment by Free-IPTV** [comment]
@Daddycool81 

My grammar? So if that is to be your evaluation criterion, then you should really look elsewhere! Nobody is perfect! But my collection of m3u's is one of the best! No illegal streams, all streams work too. Daily data maintenance and updates! And goodbye!!!
