### ISSUE TITLE
Access to the private repository

### ISSUE THREAD

**Issue by aKrRaC** [Free-IPTV/Countries#263]
Hey, I am an honest user of this m3u playlist for the past few months. It's for my personal use for watching Indian FTA channels and some USA Pluto TV channels at home. Kindly provide access to the new repo. I haven't provided any donations in the past neither have I contributed anything to this project ( I have no experience working with m3u playlists ). Kindly provide access to the new repo so that I can continue watching.

**Comment by Free-IPTV** [comment]
Hi @aKrRaC,

thank you for your interest in our new private repo. :-)

Our Free-IPTV project is always a lot of work. We always have in the old repo
the streams are regularly updated and new streams offered free of charge.

Therefore we ask for a small donation. The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

The minimum donation of 3 months is 3 EUR. I thank you!

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

After this process you will receive an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

**Comment by aKrRaC** [comment]
> Hi @aKrRaC,
> 
> thank you for your interest in our new private repo. :-)
> 
> Our Free-IPTV project is always a lot of work. We always have in the old repo
> the streams are regularly updated and new streams offered free of charge.
> 
> Therefore we ask for a small donation. The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.
> 
> The minimum donation of 3 months is 3 EUR (1 EUR per month). I thank you!
> 
> https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)
> 
> After this process you will receive an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:
> 
> https://github.com/Free-IPTV

**Comment by aKrRaC** [comment]
I would love to donate but I can't for now. Anyways thanks for the m3u's you provided free of charge

**Comment by Free-IPTV** [comment]
No problem, then you donate later. 1 EUR per month is really not much. ;-)
