### ISSUE TITLE
Requesting access

### ISSUE THREAD

**Issue by lxle** [Free-IPTV/Countries#264]
Long time user of your list. Would also like to contribute a working stirr epg.

**Comment by Free-IPTV** [comment]
Hi @lxle,

thank you for your interest in our new private repo. :-)

Our Free-IPTV project is always a lot of work. We always have in the old repo
the streams are regularly updated and new streams offered free of charge.

Therefore we ask for a small donation. The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

The minimum donation of 3 months is 3 EUR  (1 EUR per month). I thank you!

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

After this process you will receive an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

**Comment by pippolive** [comment]
Hallo, ich habe bereits gespendet

**Comment by Free-IPTV** [comment]
Hi @all

**The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the PRIVATE repo!**
