### ISSUE TITLE
Geonsey  don´t spam your Bullshit here 

### ISSUE THREAD

**Issue by geonsey** [Free-IPTV/Countries#266]
Bullshit removed - fuck you!

**Comment by protecteur** [comment]
Why are you charging folks for stuff that is readily available for free on the internet? 

By the way asking for a donation for access to a  playlist is highly illegal because you are profiting off the networks streams without there written consent! However just asking for a voluntary donation is not illegal! 

Responding with vulgar ignorant comments is also against GitHub policies!

What I see and get out of all of this is that you took the opportunity to take down your playlist and blame others for copying your work when you are doing the exact same thing as them on the grand scene of things. Taking it down was all about finding the perfect smoke and mirror scenario to start charging innocent folks money for something that was already available for free on the internet with the excuse of folks stealing your work.

Folks just use google and you will find pretty close to the same playlist that's been around before he even started his GitHub! Don't get fooled by paying for something that is already available for free!

**Comment by Free-IPTV** [comment]
Hi @protecteur,

Such well-kept and daily updated meu's are not freely available on the Internet. If so, they also stole our work. 

If you want to spam around with your bullshit, do that in your repo!
