### ISSUE TITLE
Access request

### ISSUE THREAD

**Issue by fparri** [Free-IPTV/Countries#269]
Requesting access to the new private list :)

**Comment by Free-IPTV** [comment]
Hi @fparri 

thank you for your interest in our new private repo. :-)

Our Free-IPTV project is always a lot of work. We always have in the old repo
the streams are regularly updated and new streams offered free of charge.

Therefore we ask for a small donation. **The donation is NOT for the streams, they are free. The donation is for the daily work on the M3Us.** The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

The minimum donation of 3 months is 3 EUR  (1 EUR per month). I thank you!

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

After this process you will receive an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

**Comment by fparri** [comment]
Check your PayPal :)

**Comment by Free-IPTV** [comment]
Hi @fparri,

I sent the invitation to you. Thank you. :-)

**Comment by Free-IPTV** [comment]
Hi @all

**The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the PRIVATE repo!**
