### ISSUE TITLE
Request for Access

### ISSUE THREAD

**Issue by heiler** [Free-IPTV/Countries#275]

**Comment by Free-IPTV** [comment]
Sorry, at the moment no new users. One of our special freinds has try to manipulate a fork in our new PRIVATE repo.

This attempt has now been reported to Github support!

![Zhorro](https://user-images.githubusercontent.com/45691270/113681238-06fd0880-96c2-11eb-8b9b-5d0af02a7e7d.jpg)

**Comment by robgarib** [comment]
Hi
i'm Roberto from Italy.
I have sent you some weeks ago some Italian Channels like robgarib.
I use the list for personal use for me and my family
Can i access to your new repo?
Thanks

**Comment by Free-IPTV** [comment]
https://github.com/Free-IPTV/Countries/issues/275#issuecomment-813930589

**Comment by petra1000** [comment]
hello, 
For some reason it did not go though, so I resent it, you now see 3.25 Eur, I live in the usa, I hope it goes through this time

**Comment by petra1000** [comment]
why are some people Jerks and ruin it for the rest of us?

**Comment by petra1000** [comment]
The trans id si 77552682YY1180847

**Comment by Free-IPTV** [comment]
> 
> 
> The trans id si 77552682YY1180847

Money send back. 2,85 EUR is not 3,00. Bye

**Comment by Free-IPTV** [comment]
> 
> 
> Hi
> i'm Roberto from Italy.
> I have sent you some weeks ago some Italian Channels like robgarib.
> I use the list for personal use for me and my family
> Can i access to your new repo?
> Thanks

Hi @robgarib ,

okay, you are not new user! At January you help us! :-)

thank you for your interest in our new private repo. :-)

Our Free-IPTV project is always a lot of work. We always have in the old repo
the streams are regularly updated and new streams offered free of charge.

Therefore we ask for a small donation. The donation is NOT for the streams, they are free. The donation is for the daily work on the M3Us. The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

**The minimum donation of 3 months is 3 EUR (1 EUR per month). NOT $ or other, only EUR. Outside EUROPE + 25% TAX (PAYPAL). See it for us as an estimate for the immense work. I thank you!**

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

After this process you will receive an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

You will have the invitation and access new private repo by the latest tomorrow morning (Europe time). :-)

The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the PRIVATE repo!

**Comment by Free-IPTV** [comment]
> 
> 
> Hi
> i'm Roberto from Italy.
> I have sent you some weeks ago some Italian Channels like robgarib.
> I use the list for personal use for me and my family
> Can i access to your new repo?
> Thanks

Hi @robgarib,

can you support us regularly with new streams? If you not only use our new repo, but also support us, we can talk about whether you can come in that way, okay?

**Comment by robgarib** [comment]
Hi
The only thing I can do is send to you some streams taken from Italian 
forums or groups that don't have limitation of use
Best regards



In data 7 aprile 2021 18:00:03 Free-IPTV ***@***.***> ha scritto:

**Comment by Free-IPTV** [comment]
Hmm... So we don't want to get streams from others, we look for them ourselves. This also distinguishes us from many who provide m3u's freely ... they all steal from each other. We distance ourselves from that.
