### ISSUE TITLE
Access request

### ISSUE THREAD

**Issue by iheinrich** [Free-IPTV/Countries#280]
Hello,

First: thank you a lot for the good (and hard) work you are doing!
Sorry to hear that the, sadly, usual "let's grab what we can to make a quick buck and don't care about anybody else" mindlessness has hit you too.

I'm a Kodi user and the Free-IPTV lists are the basis for my private TV streaming.
Please grant me access to your private repo.

Thanks & regards,
Ingo (from Germany)

**Comment by Free-IPTV** [comment]
Hi @iheinrich,

thank you for your interest in our new private repo. :-)

Our Free-IPTV project is always a lot of work. We always have in the old repo
the streams are regularly updated and new streams offered free of charge.

Therefore we ask for a small donation. **The donation is NOT for the streams, they are free, access to private repo also free. 

The donation is for the daily work on the M3Us.** The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

**The minimum donation of 3 months is 3 EUR (1 EUR per month). NOT $ or other, only EUR. Outside EUROPE + 25% TAX (PAYPAL). See it for us as an estimate for the immense work. I thank you!**

It is of course voluntary, it should only be an appraisal of our work.

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

After this process you will receive an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

**You will have the invitation and access new private repo by the latest next morning (Europe time). :-)**

The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the PRIVATE repo!

P.S Kennen wir uns vom Forum Kodinerds??? Haha, mich haben da ja einige Klugscheisser rausgeekelt, wegen NEID und Missgunst. Seit dann ist das Thema IPTV dort eh tot. ;-)

**Comment by Free-IPTV** [comment]
Hi @iheinrich,

schreib mich per Mail an! freeiptv-github@gmx.de

Ich lösche das danach hier!
