### ISSUE TITLE
Greetings from Germany

### ISSUE THREAD

**Issue by Penaus** [Free-IPTV/Countries#283]

**Comment by Penaus** [comment]
Hello :)
I'd like to get access to the new repo.
Thanks in advance and greetings from germany ^^

**Comment by Free-IPTV** [comment]
Hi @Penaus,

has you read the rules for the new repo in the Readme?

In our new (private) repo is a lot different than usual!

Thank you for your interest in our new private repo. :-)

Our Free-IPTV project is always a lot of work. We always have in the old repo
the streams are regularly updated and new streams offered free of charge.

Therefore we ask for a small donation. **The donation is NOT for the streams, they are free, access to private repo also free. 

The donation is for the daily work on the M3Us.** The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

**The minimum donation of 3 months is 3 EUR (1 EUR per month). NOT $ or other, only EUR please. Outside EUROPE 3,50 EUR (TAX PAYPAL). See it for us as an estimate for the immense work. I thank you!**

It is of course voluntary, it should only be an appraisal of our work.

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

After this process you will receive an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

**You will have the invitation and access new private repo by the latest next morning (Europe time). :-)**

The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the PRIVATE repo!

**Comment by Penaus** [comment]
Thanks for your fast answer.
ive got one question prior.
i use your m3u's with kodi + iptv merge to stream my german public tv.
if the new repo is private there arent any github raw links anymore?
because in iptv merge i only can enter urls, paths to file or addons.
thanks in advance

**Comment by Free-IPTV** [comment]
Details gebe ich hier nicht öffentlich raus.

**Comment by Free-IPTV** [comment]
Hi @Penaus,

schreib mich per Email an: freeiptv-github@gmx.de

Danach. lösche ich das hier!
