### ISSUE TITLE
Access

### ISSUE THREAD

**Issue by Tinkie** [Free-IPTV/Countries#287]
Please give me access to your grate work

**Comment by Free-IPTV** [comment]
Hi @Tinkie 

did you read the readme carefully beforehand?

https://github.com/Free-IPTV/Countries/blob/master/README.md

**Comment by Tinkie** [comment]
Yes

**Comment by Free-IPTV** [comment]
Hi @Tinkie ,

thank you for your interest in our new private repo. :-)

Our Free-IPTV project is always a lot of work. We always have in the old repo
the streams are regularly updated and new streams offered free of charge.

Therefore we ask for a small donation. **The donation is NOT for the streams, they are free, access to private repo also free.** 

The donation is for the daily work on the M3Us.** The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

**The minimum donation of 3 months is 3 EUR (1 EUR per month). NOT $ or other, only EUR please. Outside EUROPE 3,50 EUR (TAX PAYPAL). See it for us as an estimate for the immense work. I thank you!**

It is of course voluntary, it should only be an appraisal of our work.

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

After this process you will receive an invitation at your Github-Email with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

**You will have the invitation and access new private repo by the latest next morning (Europe time). :-)**

The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the PRIVATE repo!

**Comment by Free-IPTV** [comment]
Okay, text "How to" above deleted. Topic done.
