### ISSUE TITLE
IF YOU WANT TO ACCESS OUR NEW PRIVATE REPO

### ISSUE THREAD

**Issue by fireblade64** [Free-IPTV/Countries#363]
I agree with these rules. Please can you give me a private account. Thank you.

**Comment by criwave8888** [comment]
I agree with the rules! I’d like to have access too. Thank you

**Comment by Free-IPTV** [comment]
Hi @fireblade64,


Thank you for your interest in our collection of over 80 m3u' and at the moment exact 4127 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

Please include your Github username in the email. After that, I'll delete this issue here.
