### ISSUE TITLE
request for other TVS USA channels

### ISSUE THREAD

**Issue by triponmoon** [Free-IPTV/Countries#39]
requesting the addition of remaining TVS channels:
https://www.watchyour.tv/channels.php

thanks in advance. you're doing a great job with this list.

**Comment by Free-IPTV** [comment]
Hi Triponmoon,

the streams from this website doesn´t work for a long time because there are token= 

Look for yourself:

http://nrpus.bozztv.com/36bay2/gusa-tvs/tracks-v1a1/index-1607695596-now.m3u8?nimblesessionid=71520910&token=4d4d350fd92471238b4bc440c3ac9dd3

http://nrpus.bozztv.com/36bay2/gusa-tvs/index-1607695596-now.m3u8?token=4d4d350fd92471238b4bc440c3ac9dd3

I can't do anything about that, I'm sorry.

Greetings from Germany

**Comment by Free-IPTV** [comment]
I has find an way, i can add some streams but not all. :-)

**Comment by Free-IPTV** [comment]
I habe make an update, only 2 channels i can add, these without Token=
