### ISSUE TITLE
-- Blocked because of your stupid mails! --

### ISSUE THREAD

**Issue by reader213** [Free-IPTV/Countries#398]
hello,
please give me access to the repo

**Comment by Free-IPTV** [comment]
Hi,

Thank you for your interest in our collection of over 80 m3u' and at the moment more than 4600 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

Please include your Github username in the email. After that, I'll delete the mail-address here, otherwise you will receive countless mails from others without an issue ;-)

**Comment by Free-IPTV** [comment]
Now that you're making us look stupid via email, making claims that aren't true, your account is blocked from our profile here! Learn to behave yourself first and stop making us look stupid via email!
