### ISSUE TITLE
Asking about access to repo

### ISSUE THREAD

**Issue by Nepose** [Free-IPTV/Countries#399]
Hi, I agree to the new rules and wanted to say thanks for your work with collecting streams. I've used your m3u in my private MAG 322 before. Could you give me access to new repo?

**Comment by Free-IPTV** [comment]
Hi Nepose,

it looks like you are also programming software for the MAG-BOX. 

There is not simply an access to the M3u's, because we can not see what is done with the m3u's then.

A commercial use is only possible if new rules for this use are defined by us. If you are interested in such a cooperation, you can contact us by email:  freeiptv-github@gmx.de

Please include your Github username in the email. After that, I'll delete the mail-address here, otherwise you will receive countless mails from others without an issue ;-)

**Comment by Free-IPTV** [comment]
Okay, no mail is also a answered. Issued closed, has probably settled with it! ;-)
