### ISSUE TITLE
repo access

### ISSUE THREAD

**Issue by naimore** [Free-IPTV/Countries#400]
hello buddy,
please give me access, thanks

**Comment by Free-IPTV** [comment]
Hi Naimore,

Thank you for your interest in our collection of over 80 m3u' and at the moment more than 4600 free and legal streams.

Just like that, there is no access via an ISSUE anyway. For further information please contact me per email: freeiptv-github@gmx.de

Please include your Github username in the email. After that, I'll delete the mail-address here, otherwise you will receive countless mails from others without an issue ;-)
