### ISSUE TITLE
Access to private repo

### ISSUE THREAD

**Issue by nicodelux** [Free-IPTV/Countries#403]
Hello,

Just wanted to ask you if I can access to your private repo? I've read the rules, I accept them. 
Thanks in advance.
Thank you for your work and your invested time.
:)

**Comment by Free-IPTV** [comment]
Hi Nicodelux,

Thank you for your interest in our collection of over 80 m3u' and at the moment more than 4600 free and legal streams.

Just like that, there is no access via an ISSUE anyway. For further information please contact me per email: freeiptv-github@gmx.de

Please include your Github username in the email. After that, I'll delete the mail-address here, otherwise you will receive countless mails from others without an issue ;-)

**Comment by Free-IPTV** [comment]
Mail-address above removed. There is comming no mail from you.
