### ISSUE TITLE
Private Repo

### ISSUE THREAD

**Issue by ErAzOr2k** [Free-IPTV/Countries#407]
Hello,

can I get access to your private repo? I agree to your conditions. 
Thank you!

Regards,

ErAzOr2k

**Comment by bruinfan000** [comment]
Hi Buddy i agree to  the conditions can i get the private repo.Thanks

**Comment by Free-IPTV** [comment]
> 
> 
> Hello,
> 
> can I get access to your private repo? I agree to your conditions.
> Thank you!
> 
> Regards,
> 
> ErAzOr2k

Hi @ErAzOr2k,

thank you for your interest in our collection of over 80 m3u' and at the moment more than 4600 free and legal streams.

Just like that, there is no access via an ISSUE anyway. For further information please contact me per email: freeiptv-github@gmx.de

Please include your Github username in the email. After that, I'll delete the mail-address here, otherwise you will receive countless mails from others without an issue ;-)

**Comment by Free-IPTV** [comment]
> 
> 
> Hi Buddy i agree to the conditions can i get the private repo.Thanks

Hi @bruinfan000!

I think, you has problems to read the test in the readme! There is standig:

**PLEASE make a new ISSUE and don´t write in existing ISSUE.**
