### ISSUE TITLE
Access Request to private reep

### ISSUE THREAD

**Issue by YasirJilani** [Free-IPTV/Countries#409]
Hello, 

I would like to request access to the private repo,
 I am not an old member on GitHub and I do contribute as well. 
Please do consider me.

Thank you

**Comment by Free-IPTV** [comment]
Hi @YasirJilani 

thank you for your interest in our collection of over 80 m3u' and at the moment more than 4600 free and legal streams.

Just like that, there is no access via an ISSUE anyway. For further information please contact me per email: freeiptv-github@gmx.de

Please include your Github username in the email. After that, I'll delete the mail-address here, otherwise you will receive countless mails from others without an issue ;-)
