### ISSUE TITLE
TVN

### ISSUE THREAD

**Issue by lrm864** [Free-IPTV/Countries#424]
Hello, I have a question for you regarding your stream for TVN in your Korea playlist. TVN is a paid TV channel in South Korea, and requires a subscription via cable, satellite, or IPTV such as TVING to view the channel. Looking at the IP address and its channels, it looks like mostly the streams are from Astro, a major pay tv provider in Malaysia.

The IP address is not from Malaysia, and from what I am looking in search results is that the IP is from the Netherlands, which is telling me that the stream is not legitimate.
http://50.7.161.82:8278/

So can you tell me how you came across the TVN stream please?

**Comment by Free-IPTV** [comment]
> 
> 
> Hello, I have a question for you regarding your stream for TVN in your Korea playlist. TVN is a paid TV channel in South Korea, and requires a subscription via cable, satellite, or IPTV such as TVING to view the channel. Looking at the IP address and its channels, it looks like mostly the streams are from Astro, a major pay tv provider in Malaysia.
> 
> The IP address is not from Malaysia, and from what I am looking in search results is that the IP is from the Netherlands, which is telling me that the stream is not legitimate.
> http://50.7.161.82:8278/
> 
> So can you tell me how you came across the TVN stream please?

Hi @lrm864,

The stream ist deleted in the next update, thanks for your important information!

A tracert is ending at the router from fdcservers.net (149.14.141.10).
The IP 50.7.161.82 is registered with FDCservers.net and located in Amsterdam, Netherlands. 
So you are right! Why should a stream from Korea are sending from Netherlands!

Greeting

Free-IPTV

**Comment by Free-IPTV** [comment]
Hi @lrm864 ,

since you seem to be looking for illegal streams, why don't you make an issue there???

GITHUB/IPTV-IRG - DCMA comes probably there soon, I think...

MTVHitsEurope
https://github.com/iptv-org/iptv/pull/3338/commits/51956bfbdf12112bc5e9b0ad265a3119d7611ffc

Disney Channel Spain
https://github.com/iptv-org/iptv/pull/3325/commits/d67e63d32b974b97561c2d0a0c844504dd5a2547

Disney Channel Japan
https://github.com/iptv-org/iptv/pull/3631/commits/6134be33540eab050971ae2bc750e99082841145

BT Sport 1 and 2
https://github.com/iptv-org/iptv/pull/3304/commits/dc8f4805e6fb5e02b037cf6be282194c7a3708db

MTV 80´s
Issue - not legal, .AZ is NOT the original provider, where send the streams:
https://github.com/iptv-org/iptv/issues/3477

All streams with 163.172.209.107, this are NOT the original provider, where send the streams:
https://github.com/iptv-org/iptv/pull/3634/commits/82442e3ed55d4e029989490bb69d619adccee310
https://github.com/iptv-org/iptv/pull/3634/commits/64e23b989af89f8fb619bf09b8bf7ccd7cf7f1ee

and more, all streams there:
https://github.com/iptv-org/iptv/pull/3634

and many more in this repo!

**Comment by lrm864** [comment]
To remove a channel in that repository, there needs to be a DMCA link, which there is none. So I have no clue what to put down on how to ask for a channel to be removed, or just to enquire about the channel.

But about that MTV 80's stream (the former VH1 Classics), that stream is an official stream provided by Clip TV, a legal IPTV company in the country of Azerbaijan as listed here:
https://ntrc.gov.az/en/category/iptv-operators
https://ntrc.gov.az/en/news/436
The stream is an official stream, and I would argue that Clip TV is an original provider of the stream. Now should the stream be there at all? Well, yes and no since it is an official stream, but the stream should be viewed to those subscribers instead of just being out in the open.

**Comment by Free-IPTV** [comment]
They violate some of the rights of others, we don't need to talk about that any further. One of the EPG-file also infringes on some of the rights of others. 

All streams with 163.172.209.x are also illegal, they are NOT the streams of the original providers.  And so on... and so on...

Bye
