### ISSUE TITLE
ServusTV

### ISSUE THREAD

**Issue by menthenchocolat** [Free-IPTV/Countries#76]
**First things first: Big thanks for your work!!!**

Issue: Could you move "ServusTV" (currently in DE01_GERMANY.m3u)
further down or put it into another list?

I find it quite disturbing to have this sitting right next to and among publicly funded, reputable stations like "Das ERSTE", "ZDF", "ARTE", "3Sat".

"ServusTV" is a private TV channel, owned and funded by right leaning billionaire Dietrich Mateschitz (owner of Red Bull and with an estimated 23.000.000.000€ by far the richest man of Austria). ([ServusTV on Wikipedia](https://de.wikipedia.org/wiki/ServusTV))

"ServusTV" has been criticized in the past for giving a platform to leading activists of the fascist German Identitarian Movement ([Identitarian Movement on Wikipedia](https://en.wikipedia.org/wiki/Identitarian_movement)).

In 2020 ServusTV hosted the "Corona Quartett": A weekly platform for unchecked, unsubstantiated and potentially dangerous lies about the worldwide covid-19 pandemic.

**Comment by Free-IPTV** [comment]
Hi menthenchocolat, 

why do you find this unsettling? Sorry, I can't understand that. **Remember, my repo is only here because I want to make my M3U's available to others. I use the channel lists in Kodi and use them privately. Since I also often watch Servus TV, this channel is right up at the beginning. If you don't like this, then you don't have to use my lists.** ;-)

Greetings from Germany.

**Comment by Free-IPTV** [comment]
Hi menthenchocolat,,

keine Antwort ist auch eine Antwort! Issue geschlossen!
