### ISSUE TITLE
+ 2 french channels

### ISSUE THREAD

**Issue by ShaolinAssassin** [Free-IPTV/Countries#79]
Hi ! Thanks for your work with your lists. Here are 2 streams missing in the French list : 

#EXTINF:-1 tvg-id="" tvg-name="BFM TV" tvg-logo="https://i.ibb.co/kckRLh5/bfm.png" group-title="FRANCE",BFM TV
https://bfmtvalive1-a.akamaihd.net/1992d859ea9c46a4a5108ec10e1385b5/eu-central-1/876450610001/7b4151e1e2434a7cacdb9936db7a7910/playlist_ssaiM.m3u8

#EXTINF:-1 tvg-id="" tvg-name="Chérie 25" tvg-logo="https://i.ibb.co/R3KG4L9/cherie25.png" group-title="FRANCE",Chérie 25
https://cherie25hls-lh.akamaihd.net/i/cherie25hls_1@579096/master.m3u8 

Not a big loose but well...

BTW, in FR01_FRANCE.m3u, there are 2 typos (actually, same typo, but twice) : it should be "TF1", not "TF 1" here : 
https://github.com/Free-IPTV/Countries/blob/fb0314ab6dcec1a4e707731498aa2a1c7069a70c/FR01_FRANCE.m3u#L134
https://github.com/Free-IPTV/Countries/blob/fb0314ab6dcec1a4e707731498aa2a1c7069a70c/FR01_FRANCE.m3u#L136 

Have a nice day !

**Comment by Free-IPTV** [comment]
Hi ShaolinAssassin,

the first stream, BFM TV, doesn´t work. I have also some streams BFM in ma M3U: BFM Business, BFM Paris, Grand Lille, Lyon and Grand Littoral!

The second stream, Chérie 25, also doesn´t work. I thing it´s GEO-Blocking and in my M3U´s are only free streams, they work in all countrys.

The name TF1 will be corrected in the next update.

Thank you for your help.

**Comment by ShaolinAssassin** [comment]
Hi @Free-IPTV ! 

1) It seems that there is a problem on BFMTV side : the video stream doesn't work either on their own website : https://www.bfmtv.com/en-direct/ (whereas BFM Paris works for example) ! Please check later when they fixed the issue. And yeah, i know about these others, they are the local streams for some french cities. 

2) Weird, it works here (but yeah, it tooks like 15-20 seconds to load). And it's not supposed to be geo-blocked. Oh well, nevermind. 

Have a nice day !

**Comment by Free-IPTV** [comment]
I have now tested all streams from BFM TV again, none of them work, so that's done for now:
https://bfmtvalive1-a.akamaihd.net/1992d859ea9c46a4a5108ec10e1385b5/eu-central-1/876450610001/profile_3/14ce480ae0b94756aa10744f36a47726/chunklist_ssaiV.m3u8

https://bfmtvalive1-a.akamaihd.net/1992d859ea9c46a4a5108ec10e1385b5/eu-central-1/876450610001/profile_2/14ce480ae0b94756aa10744f36a47726/chunklist_ssaiV.m3u8

https://bfmtvalive1-a.akamaihd.net/1992d859ea9c46a4a5108ec10e1385b5/eu-central-1/876450610001/profile_0/14ce480ae0b94756aa10744f36a47726/chunklist_ssaiV.m3u8

https://bfmtvalive1-a.akamaihd.net/1992d859ea9c46a4a5108ec10e1385b5/eu-central-1/876450610001/profile_1/14ce480ae0b94756aa10744f36a47726/chunklist_ssaiV.m3u8

https://bfmtvalive1-a.akamaihd.net/1992d859ea9c46a4a5108ec10e1385b5/eu-central-1/876450610001/7b4151e1e2434a7cacdb9936db7a7910/playlist_ssaiM.m3u8

**But there are new streams that can otherwise only be received with a Samsung TV (Samsung TV Plus). The streams are broadcast freely via wurl or amagi. The 4 channels (action, comedy, drama and spotlight) are also included. :-) So have a nice day. :-)**
