### ISSUE TITLE
Add images to GitHub instead of imgur

### ISSUE THREAD

**Issue by fossdd** [Free-IPTV/Countries#85]
Currently the files are using imgur image links. imgur is properitary and not open source

So, maybe upload the images as SVG (or PNG/JPG :weary:) in the Git repository and replace all links with the github raw links of the new images.

I know this is a lot of work.

(Oh, and the forks have to use the images of our repository. Yes, i guess this is okay for them :smiley_cat:)

**Comment by Free-IPTV** [comment]
Hi fossdd,

sorry, I don't have the time either. There are now just over 3000 streams here in my repo. I need the little time I have to look after the M3U's here. Sorry, is not possible at the moment.

Greeting from Germany

**Comment by fossdd** [comment]
Yeah, of course. I know what this is for a huge work. Greetings back from Germany. :smile:

**Comment by Free-IPTV** [comment]
Okay. :-)

**Comment by CHJ85** [comment]
@fossdd That's a horrible idea. If Microsoft decides to shut down this github, he'll lose everything if he uploads the logos to github. Also, why do you care whether or not they're on an open source platform? Github is owned by Microsoft, which is a far worse company with a more suspect track record than imgur. The benefit to being open source is the transparency between the company and the developer and the end user. So just because the platform is open source, doesn't mean it's better. And who cares whether or not imgur wants to sell these TV logo images to some ad company or whatever? They're just TV logos. And besides Github is not gonna stay FOSS forever. Microsoft will eventually force their users to switch license from GNU to MIT and purge all GNU projects. So in other words, a ton of work for nothing.

**Comment by Free-IPTV** [comment]
No panic. If at some point Github no longer exists, I will open an account with another provider. Then copy the project over there and it goes on. ;-)

Should IMGUR at some point no longer exist, no problem either. The streams are primarily important, the logos are only secondary. The streams also run without logos. Always stay cool. ;-)

**Comment by CHJ85** [comment]
@Free-IPTV GIthub will always be around.
It's a huge revenue source for Microsoft.
But like you said, there are alternatives. GitLab is a great example.

**Comment by fossdd** [comment]
GitLab is also by a commercial company. The only difference is that you can host GitLab yourself and it's Open Source, but it's better then GitHub. Maybe take a look at https://codeberg.org/ witch is a https://gitea.io hosted.

**Comment by Free-IPTV** [comment]
Hi foodd,

Just a simple question. Why are you still on Github with your repos if you're so worried about my repo ???

**Comment by fossdd** [comment]
I'm not worried. I know the good sides of GitHub, like the big community. But also the negative sides. 😄

**Comment by Free-IPTV** [comment]
Hi fossdd,

so the only negative thing I feel here are the ancient forks. Complete idiots who simply create a fork and then don't care anymore. As the owner of a repo, you should be able to delete these forks. That would lead to the fact that a fork is not created here at Github in order to enrich itself!

**Comment by fossdd** [comment]
I don't understand? What should I do?

**Comment by Free-IPTV** [comment]
This Issue is closed.
